openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8088
    description: Generated server url
tags:
  - name: Elastic efast API
    description: Documentation for eFast API
  - name: Aggregations API. UC-02+UC-03
    description: Documentation for Searching+Filtering menu eFast API
  - name: Car API
    description: Documentation for Car API
  - name: Index API. UC-01
    description: /index. Documentation for Index endpoints eFast API
paths:
  
  /api/efast/v1/vehiculos:
    get:
      tags:
        - Aggregations API. UC-02+UC-03
      operationId: findAggregates
      parameters:
        - name: pag
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: tam
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: tiposElectrico
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: tiposVehiculo
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: cajaCambio
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: numPlazas
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: maximoKm
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: maximoKmStr
          in: query
          required: false
          schema:
            type: string
        - name: idVehiculo
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: marcaVehiculo
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: ciudadesVehiculo
          in: query
          required: false
          schema:
            type: string
            default: Madrid
        - name: fechaHoraIni
          in: query
          required: true
          schema:
            type: string
            default: 05-03-2024T07:00
        - name: fechaHoraFin
          in: query
          required: true
          schema:
            type: string
            default: 08-03-2024T18:00
        - name: ciudadesDevolverVehiculo
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehiculosQueryResponse'
  /api/efast/v1/vehiculosF:
    get:
      tags:
        - Aggregations API. UC-02+UC-03
      summary: ' endpoint FINAL(sin F)'
      description: ' Buscar(UC-02) y filtrar(UC-03) vehiculos disponibles en alquiler. '
      operationId: aggregates
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: tiposElectrico
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: tiposVehiculo
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: cajaCambio
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: numPlazas
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: maximoKm
          in: query
          required: false
          schema:
            type: integer
            format: int64
        - name: maximoKmStr
          in: query
          required: false
          schema:
            type: string
        - name: idVehiculo
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: marcaVehiculo
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: ciudadesVehiculo
          in: query
          required: true
          schema:
            type: string
        - name: fechaHoraIni
          in: query
          required: true
          schema:
            type: string
        - name: fechaHoraFin
          in: query
          required: true
          schema:
            type: string
        - name: ciudadesDevolverVehiculo
          in: query
          required: false
          schema:
            type: string
        - name: aggregate
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehiculosQueryResponse'
  
  /api/efast/v1/propiedades:
    get:
      tags:
        - Index API. UC-01
      operationId: buscarTiposElectrico_1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  
  /api/efast/v1/ciudades:
    get:
      tags:
        - Index API. UC-01
      operationId: findCityCars
      parameters:
        - name: nombre
          in: query
          required: true
          schema:
            maxLength: 10
            minLength: 0
            type: string
        - name: ciudadesDevolverVehiculos
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCitiesDTO'
  
components:
  schemas:
    Caracteristicas:
      type: object
      properties:
        autonomiaKm:
          type: integer
          format: int32
        año:
          type: integer
          format: int32
        cajaCambio:
          type: string
        descripcion:
          type: string
        etiquetaECO:
          type: boolean
        litros:
          type: integer
          format: int32
        maximodeKm:
          type: integer
          format: int64
        numeroBolsasmaletero:
          type: integer
          format: int32
        numplazas:
          type: integer
          format: int32
        tipoVehiculo:
          type: string
        altoConfort:
          type: boolean
        altasPrestaciones:
          type: boolean
        perfectoEstado:
          type: boolean
    Coordinates:
      type: object
      properties:
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
    Extras:
      type: object
      properties:
        gps:
          type: boolean
        sillaBebe:
          type: boolean
        proteccionenCarretera:
          type: boolean
        exenciondeFranquicia:
          type: integer
          format: int32
        opcionSeguroTodoRiesgo:
          type: boolean
    GeoOficina:
      type: object
      properties:
        coordinates:
          $ref: '#/components/schemas/Coordinates'
    Precio:
      type: object
      properties:
        por1DiaEuros:
          type: integer
          format: int32
        cancelacionGratis:
          type: boolean
        ofertaEspecial:
          type: boolean
        precioOferta:
          type: integer
          format: int32
    ResponseVehiculosDTO:
      type: object
      properties:
        id:
          type: string
        alquilable:
          type: string
        caracteristicas:
          type: array
          items:
            $ref: '#/components/schemas/Caracteristicas'
        ciudades_vehiculo:
          type: array
          items:
            type: string
        extras:
          type: array
          items:
            $ref: '#/components/schemas/Extras'
        fecha_fin:
          type: string
        fecha_ini:
          type: string
        geo_oficina:
          $ref: '#/components/schemas/GeoOficina'
        imagen_url:
          type: string
        marca_vehiculo:
          type: string
        modelo_vehiculo:
          type: string
        marcay_modelo_vehiculo:
          type: string
        precio:
          type: array
          items:
            $ref: '#/components/schemas/Precio'
        tipo_vehiculo:
          type: string
        seguro:
          type: array
          items:
            $ref: '#/components/schemas/Seguro'
    Seguro:
      type: object
      properties:
        coberturaParcialcolisionFranquiciaQty:
          type: integer
          format: int32
        coberturaParcialcolisionFranquicia:
          type: boolean
        coberturaRobo:
          type: boolean
        coberturaRobocolisionFranquiciaQty:
          type: integer
          format: int32
    VehiculosQueryResponse:
      type: object
      properties:
        vehiculos:
          type: array
          items:
            $ref: '#/components/schemas/ResponseVehiculosDTO'
        aggs:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              additionalProperties:
                type: object
    ResponseCitiesDTO:
      type: object
      properties:
        ciudadesUnicas:
          uniqueItems: true
          type: array
          items:
            type: string
        